social:
  - href: https://github.com/kobaridev
    ariaLabel: Github
    title: Github
    svg: ri:github-line
  - href: https://space.bilibili.com/1536411565
    ariaLabel: BiliBili
    title: BiliBili
    svg: ri:bilibili-line
  - href: https://x.com/xzz_ya
    ariaLabel: X(twitter)
    title: X(twitter)
    svg: ri:twitter-line
  - href: https://t.me/xzz_ya
    ariaLabel: Telegram
    title: Telegram
    svg: ri:telegram-line
icp: 萌ICP备20261117号
icp_link: https://icp.gov.moe/?keyword=20261117
